refs:
  breadcumb:
    eventListeners:
      item-click:
        handler: handleBreadcumbClick
  form:
    eventListeners:
      form-change:
        handler: handleFormChange
  submitButton:
    eventListeners:
      click:
        handler: handleSubmitClick
template:
  - rtgl-view w=f h=f pv=lg:
      - rtgl-view w=f h=24 av=c ph=lg mb=md:
          - rtgl-breadcrumb#breadcumb :items=${breadcrumb}: null
      - 'rtgl-view h=1fg sv w=f style="min-height: 0;"':
          - rtgl-form#form key=${formKey} :defaultValues=${defaultValues} :form=${form} :context=${context} w=f ph=lg pv=none: null
          - 'rtgl-view h=240 aria-hidden=true style="flex: 0 0 240px;"': null
      - 'rtgl-view d=h av=c ah=e w=f g=lg ph=lg style="flex: 0 0 auto;"':
          - rtgl-button#submitButton: Submit
